routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// use Illuminate\Support\Facades\Artisan;


Route::get('/cacheclear',function(){
    \Artisan::call('config:clear');
    \Artisan::call('config:cache');
    \Artisan::call('route:clear');
    \Artisan::call('view:clear');
    \Artisan::call('cache:clear');
    return 'Clear  Cache';
});


Route::get('/emptyDB',function()
{
    $a = App\AccountDetails::where('Code','like','CA-02%')
    ->orWhere('Code','like','CA-01%')
    ->orWhere('Code','like','CA-04%')
    ->orWhere('Code','like','CL-01%')
    ->orWhere('Code','like','CL-02%')
    ->delete();
    App\Area::truncate();
    App\Bank::truncate();
    App\Brands::truncate();
    App\Category::truncate();
    App\City::truncate();
    App\CurrentStock::truncate();
    App\ExpenseVoucher::truncate();
    App\GeneralLedger::truncate();
    App\Incentives::truncate();
    App\Products::truncate();
    App\ProductsUpdateRequest::truncate();
    App\ProductSupplier::truncate();
    App\ProductSupplierUpdate::truncate();
    App\PurchaseOrder::truncate();
    App\PurchaseOrderDetails::truncate();
    App\PurchaseRequest::truncate();
    App\PurchaseRequestDetails::truncate();
    App\Quotation::truncate();
    App\QuotationDetails::truncate();
    App\Sales::truncate();
    App\SaleDetails::truncate();
    App\SaleReturn::truncate();
    App\SaleReturnDetails::truncate();
    App\Stocks::truncate();
    App\StockOut::truncate();
    App\StockOutRequest::truncate();
    App\StockOutRequestDetails::truncate();
    App\Subcategory::truncate();
    App\TransactionHistory::truncate();
    App\Unit::truncate();
    App\Vendors::truncate();
    App\VendorsUpdateRequest::truncate();
    App\Voucher::truncate();
    App\Warehouse::truncate();
    return 'ok';
});


Auth::routes();
Route::get('/', function () {
    return view('auth.login');
});
//trialBalance
////////////////// dashboard and report//////////////////////
Route::get('/pos-opening-closing','HomeController@POS_OC')->name('pos.oc');
Route::get('/dailyPLreport/warehouse/{id}','HomeController@dailyPLreportWarehouse')->name('dailyPLreportWarehouse');
Route::get('/dailyPLreport','HomeController@dailyPLreport')->name('dailyPLreport');
Route::get('/dashboard','HomeController@index')->name('dashboard');
Route::get('/pos-detail','HomeController@pos')->name('pos');
Route::get('/pos-detail/product/{id}','HomeController@posProduct')->name('pos.product');
Route::get('/pos-detail/product/code/{code}','HomeController@posProductCode')->name('pos.product.code');
Route::get('/price-checker','HomeController@priceChecker')->name('price-checker');
Route::get('/trialBalance','HomeController@trialBalance')->name('trialBalance');
Route::get('/trialBalance/excel','HomeController@trialBalanceExcel')->name('trialBalance.excel');
Route::get('/trialBalance/search/{lm}/{trial}/{period}','HomeController@trialBalanceSearchExcel')->name('trialBalance.search.excel');
Route::post('/trialBalance/search','HomeController@trialBalanceSearch')->name('trialBalance.search');

///////////////// Home controller incomeStatement Reports Route //////////////////////////////

Route::post('/reports/incomeStatementsearch','HomeController@incomeStatementSearch')->name('reports.incomeStatementsearch');
Route::get('/reports/incomeStatement','HomeController@incomeStatement')->name('reports.incomeStatement');
Route::get('/reports/incomeStatementsearch/{M}/excel/month','HomeController@incomeStatementSearchMExcel')->name('reports.incomeStatementsearchMExcel');//excel for month
Route::get('/reports/incomeStatementsearch/{M}/pdf/month','HomeController@incomeStatementSearchMPDF')->name('reports.incomeStatementsearchMpdf');//pdf for month
Route::get('/reports/incomeStatementsearch/{Y}/excel/year','HomeController@incomeStatementSearchYExcel')->name('reports.incomeStatementsearchYExcel');//excel for year
Route::get('/reports/incomeStatementsearch/{Y}/pdf/year','HomeController@incomeStatementSearchYPDF')->name('reports.incomeStatementsearchYpdf');//pdf for year
Route::get('/reports/incomeStatement/excel','HomeController@incomeStatementExcel')->name('reports.incomeStatement.excel');
Route::get('/reports/incomeStatement/pdf','HomeController@incomeStatementPDF')->name('reports.incomeStatement.pdf');

///////////////// Home controller sale costing Reports Route //////////////////////////////

Route::post('/reports/saleCostingsearch','HomeController@saleCostingSearch')->name('reports.saleCostingsearch');
Route::get('/reports/salesCosting','HomeController@salesCosting')->name('reports.salesCosting');
Route::get('/reports/saleCosting/excel','HomeController@saleCostingExcel')->name('reports.saleCosting.excel');
Route::get('/reports/saleCosting/pdf','HomeController@saleCostingPDF')->name('reports.saleCosting.pdf');
Route::get('/reports/saleCostingsearch/{M}/excel/month','HomeController@saleCostingSearchMExcel')->name('reports.saleCostingsearchMExcel');//excel for month
Route::get('/reports/saleCostingsearch/{M}/pdf/month','HomeController@saleCostingSearchMPDF')->name('reports.saleCostingsearchMpdf');//pdf for month
Route::get('/reports/saleCostingsearch/{Y}/excel/year','HomeController@saleCostingSearchYExcel')->name('reports.saleCostingsearchYExcel');//excel for year
Route::get('/reports/saleCostingsearch/{Y}/pdf/year','HomeController@saleCostingSearchYPDF')->name('reports.saleCostingsearchYpdf');//pdf for year
Route::get('/reports/saleCostingsearch/{D}/excel/date','HomeController@saleCostingSearchDExcel')->name('reports.saleCostingsearchDExcel');//excel for one date
Route::get('/reports/saleCostingsearch/{D}/pdf/date','HomeController@saleCostingSearchDPDF')->name('reports.saleCostingsearchDpdf');//pdf for one date
Route::get('/reports/saleCostingsearch/{from}/{to}/excel/date','HomeController@saleCostingSearchDatesExcel')->name('reports.saleCostingsearchDatesExcel');//excel for date diff


//////////////// product controller /////////////////////////

Route::get('/product/datatable','ProductController@datatable')->name('product.datatable');
Route::get('/product/modal/{id}','ProductController@modal')->name('product.modal');
Route::get('/product/variants/{id}','ProductController@variants')->name('product.variants');
Route::get('/product/Pvariants/{id}','ProductController@Pvariants')->name('product.Pvariants');
Route::get('/product/Pvariantsforfinishproduct/{id}','ProductController@Pvariantsforfinishproduct')->name('product.Pvariantsforfinishproduct');
Route::get('/product/sales/{id}','ProductController@sales')->name('product.sales');
Route::get('/product/salesProduct/{id}','ProductController@salesProduct')->name('product.salesProduct');
Route::get('/product/detail/{id}','ProductController@detail')->name('product.detail');
Route::get('/product/excel','ProductController@excel')->name('product.excel');
Route::get('/product/finishProducts','ProductController@finishProducts')->name('product.finishProducts');
Route::get('/product/finishProducts/datatable','ProductController@finishProductsDatatable')->name('product.finishProducts.datatable');
Route::get('/product/finishProducts/edit/{id}','ProductController@finishProductEdit')->name('product.finishProducts.edit');
Route::put('/product/finishProducts/update/{id}','ProductController@finishProductUpdate')->name('product.finishProducts.update');
Route::get('/product/finish/excel','ProductController@Finishexcel')->name('product.finish.excel');
Route::get('/product/add','ProductController@add')->name('product.add');
Route::get('/product/stockShow/{id}','ProductController@stockShow')->name('product.stockShow');
Route::get('/product/add/show/{id}','ProductController@addSingleProduct')->name('product.add.show');
Route::get('/product/add/datatable','ProductController@addDT')->name('product.add.datatable');

Route::get('/product/productsearch/{id}','ProductController@productsearch')->name('product.productsearch');
Route::post('/product/addFinishProduct','ProductController@addFinishProduct')->name('product.addFinishProduct');
Route::resource('/product','ProductController');
Route::post('/product/status','ProductController@status')->name('product.status');
Route::post('/product/variants/status','ProductController@Vstatus')->name('product.variants.status');

/////////////////////// brands controller //////////////////////////

Route::get('/brands/datatable','BrandsController@datatable')->name('brands.datatable');
Route::get('/brands/excel','BrandsController@excel')->name('brands.excel');
Route::resource('/brands','BrandsController');
Route::post('/brands/status','BrandsController@status')->name('brands.status');

//////////////////////// unit controller ///////////////////////////

Route::get('/unit/datatable','UnitController@unitDatatable')->name('unit.datatable');
Route::resource('/unit','UnitController');
Route::post('/unit/status','UnitController@status')->name('unit.status');

///////////////////// category controller //////////////////////

Route::get('/category/datatable','CategoryController@datatable')->name('category.datatable');
Route::get('/category/excel','CategoryController@excel')->name('category.excel');
Route::resource('/category','CategoryController');
Route::post('/category/status','CategoryController@status')->name('category.status');

//////////////////// sub category controller ///////////////////////

Route::get('/subcategory/datatable','SubcategoryController@datatable')->name('subcategory.datatable');
Route::resource('/subcategory','SubcategoryController');
Route::post('/subcategory/status','SubcategoryController@status')->name('subcategory.status');

////////////// city controller ///////////////////////

resources/views/Dashboard.blade.php
@extends('layouts.master')
@section('top-styles')
    <style>
        .links {
            background: #5F9EA0;
            color: rgba(255,255,255,.8);
            display: block;
            text-align: center;
            padding-top: 10px;
            padding-bottom: 10px;
        }
    </style>
@endsection
@section('sidebar-name1')
    <li class="breadcrumb-item"><a href="{{url('')}}/dashboard">Dashboard</a></li>
@endsection
@section('header-content')

    <div class="row">
        @if (in_array('count biller',$permission))
            <div class="col-xl-3 col-md-6">
                <div class="card card-stats">
                <!-- Card body -->
                    <div class="card-body">
                        <div class="row">
                            <div class="col">
                                <h5 class="card-title text-uppercase text-muted mb-4">TOTAL BILLERS</h5>
                                <span class="h2 font-weight-bold mb-0">{{$biller}}</span>
                            </div>
                            <div class="col-auto">
                                <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow">
                                    <i class="ni ni-single-02"></i>
                                </div>
                            </div>
                            <a href="{{route('biller.index')}}" class="small-box-footer" style="padding-left: 16px">More info <i class="fa fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        @endif
        @if (in_array('count supplier',$permission))
            <div class="col-xl-3 col-md-6">
                <div class="card card-stats">
                <!-- Card body -->
                    <div class="card-body">
                    <div class="row">
                        <div class="col">
                        <h5 class="card-title text-uppercase text-muted mb-4">TOTAL SUPPLIERS</h5>
                        <span class="h2 font-weight-bold mb-0">{{$supplier}}</span>
                        </div>
                        <div class="col-auto">
                        <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow">
                            <i class="ni ni-single-02"></i>
                        </div>
                        </div>
                        <a href="{{route('supplier.index')}}" class="small-box-footer" style="padding-left: 16px">More info <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                    </div>
                </div>
            </div>
        @endif
        @if (in_array('count customer',$permission))
            <div class="col-xl-3 col-md-6">
                <div class="card card-stats">
                <!-- Card body -->
                    <div class="card-body">
                    <div class="row">
                        <div class="col">
                        <h5 class="card-title text-uppercase text-muted mb-0">TOTAL CUSTOMERS</h5>
                        <span class="h2 font-weight-bold mb-0">{{$customer}}</span>
                        </div>
                        <div class="col-auto">
                        <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow">
                            <i class="ni ni-single-02"></i>
                        </div>
                        </div>
                        <a href="{{route('customer.index')}}" class="small-box-footer" style="padding-left: 16px">More info <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                    </div>
                </div>
            </div>
        @endif
        @if (in_array('count sale person',$permission))
            <div class="col-xl-3 col-md-6">
                <div class="card card-stats">
                <!-- Card body -->
                    <div class="card-body">
                    <div class="row">
                        <div class="col">
                        <h5 class="card-title text-uppercase text-muted mb-0">TOTAL SALE PERSONS</h5>
                        <span class="h2 font-weight-bold mb-0">{{$sp}}</span>
                        </div>
                        <div class="col-auto">
                        <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow">
                            <i class="ni ni-single-02"></i>
                        </div>
                        </div>
                        <a href="{{route('saleperson.index')}}" class="small-box-footer" style="padding-left: 16px">More info <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                    </div>
                </div>
            </div>
        @endif
        @if (in_array('count brands',$permission))
            <div class="col-xl-3 col-md-6">
                <div class="card card-stats">
                <!-- Card body -->
                    <div class="card-body">
                    <div class="row">
                        <div class="col">
                        <h5 class="card-title text-uppercase text-muted mb-4">TOTAL BRANDS</h5>
                        <span class="h2 font-weight-bold mb-0">{{$brand}}</span>
                        </div>
                        <div class="col-auto">
                        <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow">
                            <i class="fa fa-bold"></i>
                        </div>
                        </div>
                        <a href="{{route('brands.index')}}" class="small-box-footer" style="padding-left: 16px">More info <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                    </div>
                </div>
            </div>
        @endif
        @if (in_array('count category',$permission))
            <div class="col-xl-3 col-md-6">
                <div class="card card-stats">
                <!-- Card body -->
                    <div class="card-body">
                    <div class="row">
                        <div class="col">
                        <h5 class="card-title text-uppercase text-muted mb-0">TOTAL CATEGORIES</h5>
                        <span class="h2 font-weight-bold mb-0">{{$cat}}</span>
                        </div>
                        <div class="col-auto">
                        <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow">
                            <i class="fab fa-cuttlefish"></i>
                        </div>
                        </div>
                        <a href="{{route('category.index')}}" class="small-box-footer" style="padding-left: 16px">More info <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                    </div>
                </div>
            </div>
        @endif
        @if (in_array('count purchase orders',$permission))
            <div class="col-xl-3 col-md-6">
                <div class="card card-stats">
                <!-- Card body -->
                    <div class="card-body">
                    <div class="row">
                        <div class="col">
                        <h5 class="card-title text-uppercase text-muted mb-0">TOTAL PURCHASE ORDERS </h5>
                        <span class="h2 font-weight-bold mb-0">{{$po}}</span>
                        </div>
                        <div class="col-auto">
                        <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow">
                            <i class="fa fa-shopping-cart"></i>
                        </div>
                        </div>
                        <a href="{{route('purchase.index')}}" class="small-box-footer" style="padding-left: 16px">More info <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                    </div>
                </div>
            </div>
        @endif
        @if (in_array('count sales',$permission))
            <div class="col-xl-3 col-md-6">
                <div class="card card-stats">
                <!-- Card body -->
                    <div class="card-body">
                    <div class="row">
                        <div class="col">
                        <h5 class="card-title text-uppercase text-muted mb-0">TOTAL SALES ORDERS</h5>
                        <span class="h2 font-weight-bold mb-0">{{$sale}}</span>
                        </div>
                        <div class="col-auto">
                        <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow">
                            <i class="fa fa-credit-card"></i>
                        </div>
                        </div>
                        <a href="{{route('sales.index')}}" class="small-box-footer" style="padding-left: 16px" >More info <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                    </div>
                </div>
            </div>
        @endif
        @if (in_array('count finish',$permission))
            <div class="col-xl-3 col-md-6">
                <div class="card card-stats">
                <!-- Card body -->
                    <div class="card-body">
                    <div class="row">
                        <div class="col">
                        <h5 class="card-title text-uppercase text-muted mb-0">TOTAL PRODUCTS</h5>
                        <span class="h2 font-weight-bold mb-0">{{$finish== null ? 0 : $finish[0]->quantity}}</span>
                        </div>
                        <div class="col-auto">
                        <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow">
                            <i class="fa fa-list-alt"></i>
                        </div>
                    </div>
                        <a href="{{route('product.index')}}" class="small-box-footer" style="padding-left: 15px">More info <i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                    </div>
                </div>
            </div>
        @endif

    </div>
@endsection

@section('content')
    <hr color="black" >
    <h3 style="text-decoration: underline"><b>QUICK LINKS</b></h3>
    <div class="row">
        @if (in_array('Add Bank',$permission))
        <div class="col-sm-3">
            <a href="{{url('')}}/bank/create" class="links"><i id="icon" class="fas fa-landmark"></i> &nbsp; Add Bank</a>
        </div>
        @endif
        @if (in_array('Add Brand',$permission))
        <div class="col-sm-3">
            <a href="{{url('')}}/brands/create" class="links"><i id="icon" class="fa fa-bold"></i>&nbsp; Add Brand</a>
        </div>
        @endif
        @if (in_array('Add Product',$permission))
        <div class="col-sm-3">
            <a href="{{url('')}}/product/create" class="links"><i id="icon" class="fa fa-list-alt"></i>&nbsp; Add Product</a>
        </div>
        @endif
        @if (in_array('Add Finish Product',$permission))
        <div class="col-sm-3">
            <a href="{{url('')}}/product/add" class="links"><i id="icon" class="fa fa-list-alt"></i>Add Finish Product</a>
        </div>
        @endif
    </div>
    <br>
    <div class="row">
        @if (in_array('Add Stock',$permission))
        <div class="col-sm-3">
            <a href="{{url('')}}/stocks/create" class="links"><i id="icon" class="fa fa-tasks"></i>&nbsp; Add Stock</a>
        </div>
        @endif
        @if (in_array('Add Purchase Order',$permission))
        <div class="col-sm-3">
            <a href="{{url('')}}/purchase/create" class="links"><i id="icon" class="fa fa-shopping-cart"></i>&nbsp; New Purchase Order</a>
        </div>
        @endif
        @if (in_array('Add Sale',$permission))
        <div class="col-sm-3">
            <a href="{{url('')}}/sales/create" class="links"><i id="icon" class="fa fa-credit-card"></i>&nbsp; New Sale Order</a>
        </div>
        @endif


    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/notifications.blade.php
@extends('layouts.master')
@section('top-styles')
<style>
    .tableview
    {
        background-color:#F0F0F0;
        padding: 20px;
        border-radius: 5px;
        border:1px solid  #e7ecf1;
    }
</style>
<style>
    #GFG {
        text-decoration: none;
    }
    thead {
	    background-color: #5F9EA0;
    }
    .modal-header{
        background: #5F9EA0 !important;
    }
</style>
@toastr_css

@section('sidebar-name1')
<li class="breadcrumb-item"><a href="{{url('')}}/notifications">All Notifications</a></li>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- Begin: life time stats -->
            <div class="card">
                <div class="card-body">
                    <div class="tabbable-line">
                        <div class="row">
                            <div class="col-md-12 col-sm-12">
                                <div class="portlet grey-cascade box">
                                    <div class="card-header" style="background: #32c5d2;">
                                        <div class="caption" style="width: -webkit-fill-available; ">
                                            <i class="fa fa-bell font-white"></i>All Notifications

                                        </div>
                                    </div>

                                    <div class="card-body">
                                        <div class="custom_datatable">

                                            <div class="table-responsive">
                                            <table id="example" class="table table-striped table-bordered" style="width:100%">
                                                    <thead>
                                                        <tr>
                                                            <th width="10%">S.No</th>
                                                            <th>Notification</th>
                                                            <th>Link</th>
                                                            <th width="30%">Action</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @php
                                                            $a = 1;
                                                        @endphp
                                                        @foreach (auth()->user()->notifications()->get() as $n)
                                                            <tr>
                                                                <td>{{$a}}</td>
                                                                <td>{{$n->data['notification']}}</td>
                                                                <td>
                                                                    <a href="{{$n->data['link']}}">
                                                                        {{$n->data['name']}}
                                                                    </a>
                                                                </td>
                                                                @if ($n->read_at == null)
                                                                    <td>
                                                                        <a href="{{route('markReadSingle',["$n->id"])}}">
                                                                            <button class="btn btn-sm btn-danger">Mark as read</button>
                                                                        </a>
                                                                    </td>
                                                                @else
                                                                    <td>
                                                                        <button class="btn btn-sm btn-success" disabled>Read</button>
                                                                    </td>
                                                                @endif
                                                            </tr>
                                                            @php
                                                                $a++;
                                                            @endphp
                                                        @endforeach
                                                    </tbody>

                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>




                    </div>
                </div>
            </div>
        </div>
        <!-- End: life time stats -->
    </div>
    @section('custom-script')
    @toastr_js
    @toastr_render

        <script type="text/javascript">
            $(document).ready(function () {
                var table = $('#example').DataTable();
            });

        </script>
    @endsection
    @endsection