routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// use Illuminate\Support\Facades\Artisan;


Route::get('/cacheclear',function(){
    \Artisan::call('config:clear');
    \Artisan::call('config:cache');
    \Artisan::call('route:clear');
    \Artisan::call('view:clear');
    \Artisan::call('cache:clear');
    return 'Clear  Cache';
});


Route::get('/emptyDB',function()
{
    $a = App\AccountDetails::where('Code','like','CA-02%')
    ->orWhere('Code','like','CA-01%')
    ->orWhere('Code','like','CA-04%')
    ->orWhere('Code','like','CL-01%')
    ->orWhere('Code','like','CL-02%')
    ->delete();
    App\Area::truncate();
    App\Bank::truncate();
    App\Brands::truncate();
    App\Category::truncate();
    App\City::truncate();
    App\CurrentStock::truncate();
    App\ExpenseVoucher::truncate();
    App\GeneralLedger::truncate();
    App\Incentives::truncate();
    App\Products::truncate();
    App\ProductsUpdateRequest::truncate();
    App\ProductSupplier::truncate();
    App\ProductSupplierUpdate::truncate();
    App\PurchaseOrder::truncate();
    App\PurchaseOrderDetails::truncate();
    App\PurchaseRequest::truncate();
    App\PurchaseRequestDetails::truncate();
    App\Quotation::truncate();
    App\QuotationDetails::truncate();
    App\Sales::truncate();
    App\SaleDetails::truncate();
    App\SaleReturn::truncate();
    App\SaleReturnDetails::truncate();
    App\Stocks::truncate();
    App\StockOut::truncate();
    App\StockOutRequest::truncate();
    App\StockOutRequestDetails::truncate();
    App\Subcategory::truncate();
    App\TransactionHistory::truncate();
    App\Unit::truncate();
    App\Vendors::truncate();
    App\VendorsUpdateRequest::truncate();
    App\Voucher::truncate();
    App\Warehouse::truncate();
    return 'ok';
});


Auth::routes();
Route::get('/', function () {
    return view('auth.login');
});
//trialBalance
////////////////// dashboard and report//////////////////////
Route::get('/pos-opening-closing','HomeController@POS_OC')->name('pos.oc');
Route::get('/dailyPLreport/warehouse/{id}','HomeController@dailyPLreportWarehouse')->name('dailyPLreportWarehouse');
Route::get('/dailyPLreport','HomeController@dailyPLreport')->name('dailyPLreport');
Route::get('/dashboard','HomeController@index')->name('dashboard');
Route::get('/pos-detail','HomeController@pos')->name('pos');
Route::get('/pos-detail/product/{id}','HomeController@posProduct')->name('pos.product');
Route::get('/pos-detail/product/code/{code}','HomeController@posProductCode')->name('pos.product.code');
Route::get('/price-checker','HomeController@priceChecker')->name('price-checker');
Route::get('/trialBalance','HomeController@trialBalance')->name('trialBalance');
Route::get('/trialBalance/excel','HomeController@trialBalanceExcel')->name('trialBalance.excel');
Route::get('/trialBalance/search/{lm}/{trial}/{period}','HomeController@trialBalanceSearchExcel')->name('trialBalance.search.excel');
Route::post('/trialBalance/search','HomeController@trialBalanceSearch')->name('trialBalance.search');

///////////////// Home controller incomeStatement Reports Route //////////////////////////////

Route::post('/reports/incomeStatementsearch','HomeController@incomeStatementSearch')->name('reports.incomeStatementsearch');
Route::get('/reports/incomeStatement','HomeController@incomeStatement')->name('reports.incomeStatement');
Route::get('/reports/incomeStatementsearch/{M}/excel/month','HomeController@incomeStatementSearchMExcel')->name('reports.incomeStatementsearchMExcel');//excel for month
Route::get('/reports/incomeStatementsearch/{M}/pdf/month','HomeController@incomeStatementSearchMPDF')->name('reports.incomeStatementsearchMpdf');//pdf for month
Route::get('/reports/incomeStatementsearch/{Y}/excel/year','HomeController@incomeStatementSearchYExcel')->name('reports.incomeStatementsearchYExcel');//excel for year
Route::get('/reports/incomeStatementsearch/{Y}/pdf/year','HomeController@incomeStatementSearchYPDF')->name('reports.incomeStatementsearchYpdf');//pdf for year
Route::get('/reports/incomeStatement/excel','HomeController@incomeStatementExcel')->name('reports.incomeStatement.excel');
Route::get('/reports/incomeStatement/pdf','HomeController@incomeStatementPDF')->name('reports.incomeStatement.pdf');

///////////////// Home controller sale costing Reports Route //////////////////////////////

Route::post('/reports/saleCostingsearch','HomeController@saleCostingSearch')->name('reports.saleCostingsearch');
Route::get('/reports/salesCosting','HomeController@salesCosting')->name('reports.salesCosting');
Route::get('/reports/saleCosting/excel','HomeController@saleCostingExcel')->name('reports.saleCosting.excel');
Route::get('/reports/saleCosting/pdf','HomeController@saleCostingPDF')->name('reports.saleCosting.pdf');
Route::get('/reports/saleCostingsearch/{M}/excel/month','HomeController@saleCostingSearchMExcel')->name('reports.saleCostingsearchMExcel');//excel for month
Route::get('/reports/saleCostingsearch/{M}/pdf/month','HomeController@saleCostingSearchMPDF')->name('reports.saleCostingsearchMpdf');//pdf for month
Route::get('/reports/saleCostingsearch/{Y}/excel/year','HomeController@saleCostingSearchYExcel')->name('reports.saleCostingsearchYExcel');//excel for year
Route::get('/reports/saleCostingsearch/{Y}/pdf/year','HomeController@saleCostingSearchYPDF')->name('reports.saleCostingsearchYpdf');//pdf for year
Route::get('/reports/saleCostingsearch/{D}/excel/date','HomeController@saleCostingSearchDExcel')->name('reports.saleCostingsearchDExcel');//excel for one date
Route::get('/reports/saleCostingsearch/{D}/pdf/date','HomeController@saleCostingSearchDPDF')->name('reports.saleCostingsearchDpdf');//pdf for one date
Route::get('/reports/saleCostingsearch/{from}/{to}/excel/date','HomeController@saleCostingSearchDatesExcel')->name('reports.saleCostingsearchDatesExcel');//excel for date diff


//////////////// product controller /////////////////////////

Route::get('/product/datatable','ProductController@datatable')->name('product.datatable');
Route::get('/product/modal/{id}','ProductController@modal')->name('product.modal');
Route::get('/product/variants/{id}','ProductController@variants')->name('product.variants');
Route::get('/product/Pvariants/{id}','ProductController@Pvariants')->name('product.Pvariants');
Route::get('/product/Pvariantsforfinishproduct/{id}','ProductController@Pvariantsforfinishproduct')->name('product.Pvariantsforfinishproduct');
Route::get('/product/sales/{id}','ProductController@sales')->name('product.sales');
Route::get('/product/salesProduct/{id}','ProductController@salesProduct')->name('product.salesProduct');
Route::get('/product/detail/{id}','ProductController@detail')->name('product.detail');
Route::get('/product/excel','ProductController@excel')->name('product.excel');
Route::get('/product/finishProducts','ProductController@finishProducts')->name('product.finishProducts');
Route::get('/product/finishProducts/datatable','ProductController@finishProductsDatatable')->name('product.finishProducts.datatable');
Route::get('/product/finishProducts/edit/{id}','ProductController@finishProductEdit')->name('product.finishProducts.edit');
Route::put('/product/finishProducts/update/{id}','ProductController@finishProductUpdate')->name('product.finishProducts.update');
Route::get('/product/finish/excel','ProductController@Finishexcel')->name('product.finish.excel');
Route::get('/product/add','ProductController@add')->name('product.add');
Route::get('/product/stockShow/{id}','ProductController@stockShow')->name('product.stockShow');
Route::get('/product/add/show/{id}','ProductController@addSingleProduct')->name('product.add.show');
Route::get('/product/add/datatable','ProductController@addDT')->name('product.add.datatable');

Route::get('/product/productsearch/{id}','ProductController@productsearch')->name('product.productsearch');
Route::post('/product/addFinishProduct','ProductController@addFinishProduct')->name('product.addFinishProduct');
Route::resource('/product','ProductController');
Route::post('/product/status','ProductController@status')->name('product.status');
Route::post('/product/variants/status','ProductController@Vstatus')->name('product.variants.status');

/////////////////////// brands controller //////////////////////////

Route::get('/brands/datatable','BrandsController@datatable')->name('brands.datatable');
Route::get('/brands/excel','BrandsController@excel')->name('brands.excel');
Route::resource('/brands','BrandsController');
Route::post('/brands/status','BrandsController@status')->name('brands.status');

//////////////////////// unit controller ///////////////////////////

Route::get('/unit/datatable','UnitController@unitDatatable')->name('unit.datatable');
Route::resource('/unit','UnitController');
Route::post('/unit/status','UnitController@status')->name('unit.status');

///////////////////// category controller //////////////////////

Route::get('/category/datatable','CategoryController@datatable')->name('category.datatable');
Route::get('/category/excel','CategoryController@excel')->name('category.excel');
Route::resource('/category','CategoryController');
Route::post('/category/status','CategoryController@status')->name('category.status');

//////////////////// sub category controller ///////////////////////

Route::get('/subcategory/datatable','SubcategoryController@datatable')->name('subcategory.datatable');
Route::resource('/subcategory','SubcategoryController');
Route::post('/subcategory/status','SubcategoryController@status')->name('subcategory.status');

////////////// city controller ///////////////////////

app/Unit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Unit extends Model
{
    protected $table = 'units';
    protected $primaryKey = 'id';
    protected $fillable = [
        'u_name',
        'created_by',
        'updated_by',
        'status'
    ];

    public function products()
    {
        return $this->belongsTo('App\Products');
    }

    public function createUser()
    {
        return $this->hasOne('App\User','id','created_by');
    }

    public function updateUser()
    {
        return $this->hasOne('App\User','id','updated_by');
    }
}

app/Http/Controllers/UnitController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Unit;
use DataTables;
use Auth;

class UnitController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        $menu_id            =   getMenuId($request);
        $permissions        =   getRolePermission($menu_id);
        return view('unit.index',compact('permissions'));
    }

    public function unitDatatable()
    {
        $unit=Unit::all();
        return DataTables::of($unit)->make();
    }

    public function status(Request $request)
    {
        // dd($request->all());
        $response['status'] = false;
        $response['message'] = 'Oops! Something went wrong.';
        $u_id = Auth::user()->id;
        $id     = $request->input('id');
        $status = $request->input('status');

        $item = Unit::find($id);
        if ($item->update(['status' => $status])) {
            $item->update([
                'status' => $status,
                'updated_by' => $u_id
            ]);
            $response['status'] = $status;
            $response['message'] = 'status updated successfully.';
            return response()->json($response, 200);
        }
        return response()->json($response, 409);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data=[
            'isEdit' =>false
        ];
        return view('unit.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'u_name'      =>  'required|string|max:255|unique:units'
        ]);
        $data['created_by'] = Auth::user()->id;
        $unit = Unit::create($data);
        if(isset($request->request_type) && $request->request_type == "ajax")
        {
            $response['message'] = 'Unit added successfully!';
            $response['unit'] = $unit;
            return response()->json($response, 200);
        }
        toastr()->success('Unit added successfully!');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Unit $unit)
    {
        if(request()->ajax())
        {
            return $unit;
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Unit $unit)
    {
        $data=[
            'isEdit' => true,
            'unit' =>$unit
        ];
        return view('unit.create',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Unit $unit)
    {
        $data = $request->validate([
            'u_name'      =>  'required|string|max:255|unique:units,u_name,'.$unit->id
        ]);
        $data['updated_by'] = Auth::user()->id;
        $unit->update($data);
        toastr()->success('Unit updated successfully!');
        return redirect(url('').'/unit');
    }
}

resources/views/unit/create.blade.php
@extends('layouts.master')
@section('top-styles')
@toastr_css
@section('sidebar-name1')
    <li class="breadcrumb-item"><a href="{{ url('')}}/unit">Unit</a></li>
    <li class="breadcrumb-item"><span>{{$isEdit ? 'Edit' : 'Add'}} Unit</span></li>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN VALIDATION STATES-->
            <div class="card" id="form_wizard_1">
                <div class="card-header">
                    <div class="caption">
                        <i class=" fa fa-balance-scale font-green"></i>
                        <span class="caption-subject font-green sbold uppercase">{{$isEdit ? 'Edit' : 'Add'}} Unit</span>
                    </div>

                </div>
                <div class="card-body">
                    <!-- BEGIN FORM-->
                    <form action="{{$isEdit ? route('unit.update',$unit->id) :  route('unit.store')}} " class="form-horizontal" method="POST"  id="unitForm">
                        @csrf
                        @if ($isEdit)
                            @method('PUT')
                        @endif
                        <div class="form-body">

                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-outline">
                                        <label >Unit Name<span class="text-danger">*</span></label>
                                        <input value="{{$unit->u_name ?? old('u_name')}}" class="form-control" type="text" placeholder="Enter Unit Name" name="u_name" >
                                        <span class="text-danger">{{$errors->first('u_name') ? 'Unit already exist or Enter unit' : null}}</span>
                                    </div>
                                </div>
                            </div>
                            <br>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-0">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </div>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
            <!-- END VALIDATION STATES-->
        </div>
    </div>

@endsection
@section('custom-script')
<script>
    $('#unitForm').validate({
        rules: {
            u_name: {
                required: true,
            },
        },
        errorElement: 'span',
        errorPlacement: function (error, element) {
            error.addClass('invalid-feedback back_error');
            element.closest('.form-outline').append(error);
        },
        highlight: function (element, errorClass, validClass) {
            $(element).addClass('is-invalid');

        },
        unhighlight: function (element, errorClass, validClass) {
            $(element).removeClass('is-invalid');
        }
    });
</script>
@toastr_js
@toastr_render
@endsection

resources/views/unit/index.blade.php
@extends('layouts.master')
@section('top-styles')
<style>
    .tableview
    {
        background-color:#F0F0F0;
        padding: 20px;
        border-radius: 5px;
        border:1px solid  #e7ecf1;
    }
</style>
<style>
    #GFG {
        text-decoration: none;
    }
    thead {
	    background-color: #5F9EA0;
    }
    .modal-header{
        background: #5F9EA0 !important;
    }
</style>
@toastr_css

@section('sidebar-name1')
<li class="breadcrumb-item"><a href="{{ url('')}}/unit">Unit</a></li>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- Begin: life time stats -->
            <div class="card">
                <div class="card-body">
                    <div class="tabbable-line">
                        <div class="row">
                            <div class="col-md-12 col-sm-12">
                                <div class="portlet grey-cascade box">
                                    <div class="card-header" style="background: #32c5d2;">
                                        <div class="caption" style="width: -webkit-fill-available; ">
                                            <i class="fa fa-balance-scale font-white"></i>View Units
                                            @if(in_array('Add',$permissions))
                                                <a id="GFG" href="{{route('unit.create')}}" class="col-md-2" style="float: right">
                                                    <button style="margin-top: -9px" type="button"  class="btn btn-block btn-info btn-md ">Add Unit</button>
                                                </a>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="portlet-body">
                                        <div class="custom_datatable">
                                            <form action="#" id="advanceSearch">
                                                <div class="tableview">
                                                <div class="row">
                                                    <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label for="">Unit Name</label>
                                                        <input type="text" name="u_name" id="autocomplete-ajax1" class="form-control" placeholder="Unit Name" style=" z-index: 2;" autocomplete="off">
                                                    </div>
                                                    </div>
                                                    <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label for="">Active Status</label>
                                                        <select name="status" class="form-control ">
                                                        <option selected="" value="">No Filter</option>
                                                        <option value="1">Active</option>
                                                        <option value="0">InActive</option>
                                                        </select>
                                                    </div>
                                                    </div>
                                                    <div class="col-md-4">
                                                    <div class="form-group">
                                                        {{-- <label for="">Unit Name</label> --}}
                                                        <label for="" style="visibility: hidden">.</label>
                                                        <button id="search" style="background: #32c5d2" class="btn btn-light-theme btn-block waves-effect waves-light">
                                                        <i class="fa fa-search pr-1"></i> Search</button>
                                                    </div>
                                                    </div>
                                                </div>
                                                </div>
                                            </form>
                                            <div class="table-responsive">
                                            <table id="example" class="table table-striped table-bordered" style="width:100%">
                                                    <thead>
                                                        <tr>
                                                            <th width="7%">S.No</th>
                                                            <th>Name</th>
                                                            <th width="15%">Action</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                    </tbody>

                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>




                    </div>
                </div>
            </div>
        </div>
        <!-- End: life time stats -->
    </div>
    @section('modal')
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog modal-lg">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Unit</h4>
                        <button type="button" class="close" data-dismiss="modal">×</button>
                    </div>
                    <div class="modal-body">

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-outline">
                                    <label >Unit Name</label>
                                    <input class="form-control" type="text" placeholder="Enter Unit Name" id="u_name" readonly>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>
    <!--End Modal-->
    @endsection
    @section('custom-script')
    @toastr_js
    @toastr_render
        {{-- view one product --}}
        <script>
            $(document).on('click','.view',function(){
                var id=$(this).attr("id");
                $.ajax({
                    url:"{{url('')}}/unit/"+id,
                    method:"GET",
                    error: function (request, error) {
                                alert(" Can't do because: " + error +request);
                            },
                    success:function(data){
                        console.log(data);
                        $('#u_name').val(data.u_name);
                    }
                });
            });
        </script>
        <script type="text/javascript">
            $(document).ready(function () {
                var table = $('#example').DataTable({
                    processing: true,
                    serverSide: true,
                    order: [[ 0, "desc" ]],
                    scrollX: true,
                    ajax: '{{route("unit.datatable")}}',
                    "columns": [{
                            "data": "id",
                            "defaultContent": ""
                        },
                        {
                            "data": "u_name",
                            "defaultContent": ""
                        },
                        {
                            "data": "status",
                            "defaultContent": ""
                        },
                    ],
                    "columnDefs": [{
                            "targets": 'no-sort',
                            "orderable": false,
                        },
                        {
                            "targets": 0,
                            "render": function (data, type, row, meta) {
                                return meta.row + 1 ;
                            },
                        },
                        {
                            "targets": -1,
                            "render": function (data, type, row, meta) {
                                var edit = '{{route("unit.edit",[":id"])}}';
                                edit = edit.replace(':id', row.id);
                                var checked = row.status == 1 ? 'checked' : null;
                                return `
                                @if(in_array('edit',$permissions))
                                    <a id="GFG" href="` + edit + `" class="text-info p-1">
                                        <button type="button" class="btn blue edit" >
                                            <i class="fa fa-edit"></i>
                                        </button>
                                    </a>
                                @endif
                                @if(in_array('show',$permissions))
                                    <button type="button" data-target="#myModal" data-toggle="modal"  class="btn green view" id="`+row.id +`">
                                        <i class="fa fa-eye"></i>
                                    </button>
                                @endif
                                @if(in_array('status',$permissions))
                                    <input class="status" type="checkbox" data-plugin="switchery" data-color="#005CA3" data-size="small" ` +
                                                checked + ` value="` + row.id + `">
                                @endif
                                `;
                            },
                        },
                    ],
                    "drawCallback": function (settings) {
                        var elems = Array.prototype.slice.call(document.querySelectorAll('.status'));
                        if (elems) {
                        elems.forEach(function (html) {
                            var switchery = new Switchery(html, {
                                color: '#007bff'
                                , secondaryColor: '#dfdfdf'
                                , jackColor: '#fff'
                                , jackSecondaryColor: null
                                , className: 'switchery'
                                , disabled: false
                                , disabledOpacity: 0.5
                                , speed: '0.1s'
                                , size: 'small'
                                });

                            });
                        }
                        $('.status').change(function () {
                            var $this = $(this);
                            var id = $this.val();
                            var status = this.checked;

                            if (status) {
                                status = 1;
                            } else {
                                status = 0;
                            }
                    // console.log(status);
                        axios
                            .post('{{route("unit.status")}}', {
                            _token: '{{csrf_token()}}',
                            _method: 'post',
                            id: id,
                            status: status,
                            })
                            .then(function (responsive) {
                            console.log('responsive');
                            // location.reload();
                            })
                            .catch(function (error) {
                            console.log(error);
                            });
                        });

                    },
                });
                $('#advanceSearch').submit(function(e){
                    e.preventDefault();
                    // var date = moment($('input[name="created_at"]').val(),'YYYY/MM/DD').format('YYYY-MM-DD');
                    // if(date === 'Invalid date')
                    // {
                    // date = '';
                    // }
                    // console.log($('.ver-status').val());
                    table.columns(1).search($('input[name="u_name"]').val());
                    table.columns(2).search($('select[name="status"]').val());
                    table.draw();
                });

            });

        </script>
    @endsection
@endsection