routes/web.php
Route::get('/productTransfer/product','ProductTransaferHistoryController@product')->name('productTransfer.product');
Route::get('/productTransfer/excel','ProductTransaferHistoryController@excel')->name('productTransfer.excel');
Route::get('/productTransfer/pdf','ProductTransaferHistoryController@pdf')->name('productTransfer.pdf');
Route::post('/productTransfer/search','ProductTransaferHistoryController@search')->name('productTransfer.search');
Route::get('/productTransfer/search/{M}/{pname}/type/{fw}/{tw}/excel/month','ProductTransaferHistoryController@searchMExcel')->name('productTransfer.searchMExcel');//excel for month
Route::get('/productTransfer/search/{Y}/{pname}/type/{fw}/{tw}/excel/year','ProductTransaferHistoryController@searchYExcel')->name('productTransfer.searchYExcel');//excel for year
Route::get('/productTransfer/search/{D}/{pname}/type/{fw}/{tw}/excel/date','ProductTransaferHistoryController@searchDExcel')->name('productTransfer.searchDExcel');//excel for one date
Route::get('/productTransfer/search/{from}/{to}/{pname}/type/{fw}/{tw}/excel/date','ProductTransaferHistoryController@searchDatesExcel')->name('productTransfer.searchDatesExcel');//excel for date diff
Route::resource('/productTransfer','ProductTransaferHistoryController');

///////////////// company controller ////////////////////////

Route::get('/company/datatable','CompanyController@datatable')->name('company.datatable');
Route::get('/company/excel','CompanyController@excel')->name('company.excel');
Route::get('/company/pdf','CompanyController@pdf')->name('company.pdf');
Route::resource('/company','CompanyController');

/////////////////// group controller //////////////////////////

Route::get('/group/datatable','GroupController@datatable')->name('group.datatable');
Route::resource('/group','GroupController');

///////////////counter controller///////////////////////////
Route::get('/counter/datatable','CounterController@datatable')->name('counter.datatable');
Route::resource('/counter','CounterController');


///////////////CounterAssignedController ///////////////////////////
Route::get('/assigned/datatable','CounterAssignedController@datatable')->name('assigned.datatable');
Route::resource('/assigned','CounterAssignedController');

/////////////// customer controller ///////////////////////

Route::post('/customer/status','CustomerController@status')->name('customer.status');
Route::get('/customer/datatable','CustomerController@datatable')->name('customer.datatable');
Route::get('/customer/excel','CustomerController@excel')->name('customer.excel');
Route::get('/customer/pdf','CustomerController@pdf')->name('customer.pdf');
Route::get('/customer/balance/{id}','CustomerController@balance')->name('customer.balance');
Route::resource('/customer','CustomerController');

///////////////// supplier controller /////////////////

Route::post('/supplier/status','SupplierController@status')->name('supplier.status');
Route::get('/supplier/datatable','SupplierController@datatable')->name('supplier.datatable');
Route::get('/supplier/excel','SupplierController@excel')->name('supplier.excel');
Route::get('/supplier/pdf','SupplierController@pdf')->name('supplier.pdf');
Route::get('/supplier/products/{id}','SupplierController@Products')->name('supplier.products');
Route::resource('/supplier','SupplierController');

////////////////// sale person controller ////////////////////////////////

Route::post('/saleperson/status','SalePersonController@status')->name('saleperson.status');
Route::get('/saleperson/datatable','SalePersonController@datatable')->name('saleperson.datatable');
Route::get('/saleperson/excel','SalePersonController@excel')->name('saleperson.excel');
Route::get('/saleperson/pdf','SalePersonController@pdf')->name('saleperson.pdf');
Route::get('/saleperson/saledetails/{month}/{id}','SalePersonController@saledetails')->name('saleperson.saledetails');
Route::resource('/saleperson','SalePersonController');

//////////////////// purchase controller  ///////////////////////////

Route::post('/purchase/search','PurchaseOrderController@search')->name('purchase.search');
Route::get('/purchaseDetail/{id}','PurchaseOrderController@purchaseDetail')->name('purchaseDetail');
Route::get('/purchase/pdf/{id}','PurchaseOrderController@pdf')->name('purchase.pdf');
Route::get('/purchase/pdf','PurchaseOrderController@pdf1');
Route::get('/purchase/grr/{no,id}','PurchaseOrderController@GRR')->name('purchase.GRR');
Route::get('/purchase/grr1/{no}','PurchaseOrderController@GRR1');
Route::get('/purchase/document/{id}','PurchaseOrderController@document')->name('purchase.document');
Route::get('/purchase/invoice/{id}','PurchaseOrderController@invoice')->name('purchase.invoice');
Route::get('/purchase/product/{id}','PurchaseOrderController@product')->name('purchase.product');
Route::get('/purchase/grn/{id}','PurchaseOrderController@GRN')->name('purchase.grn');
Route::get('/purchase/report','PurchaseOrderController@report')->name('purchase.report');
// Route::get('/purchase/excel','PurchaseOrderController@excel')->name('purchase.excel');
Route::resource('/purchase','PurchaseOrderController');
Route::post('/purchase/status','PurchaseOrderController@status')->name('purchase.status');
// Route::post('/purchase/Receiving','PurchaseOrderController@Receiving')->name('purchase.Receiving');
Route::post('/purchase/updateQuantity','PurchaseOrderController@updateQuantity')->name('purchase.updateQuantity');

//////////////////// biller controller ////////////////////////////////

Route::post('/biller/status','BillerController@status')->name('biller.status');
Route::get('/biller/datatable','BillerController@datatable')->name('biller.datatable');
Route::get('/biller/excel','BillerController@excel')->name('biller.excel');
Route::get('/biller/pdf','BillerController@pdf')->name('biller.pdf');
Route::resource('/biller','BillerController');

//////////////////// sales  controller ///////////////////////////

Route::post('/sales/search','SalesController@search')->name('sales.search');
Route::get('/sales/sync','SalesController@sync')->name('sales.sync');

Route::get('/sales/return/voucher/{id}','SalesController@voucher')->name('sales.return.voucher');

Route::get('/sales/excel','SalesController@excel')->name('sales.excel');
Route::get('/sales/search/{Y}/{c}/{s}/{ss}/{ps}/{check}/excel/year','SalesController@saleYExcel')->name('sales.saleYExcel');//excel for year
Route::get('/sales/search/{M}/{c}/{s}/{ss}/{ps}/{check}/excel/month','SalesController@saleMExcel')->name('sales.saleMExcel');//excel for month
Route::get('/sales/search/{D}/{c}/{s}/{ss}/{ps}/{check}/excel/date','SalesController@saleDExcel')->name('sales.saleDExcel');//excel for one date
Route::get('/sales/search/{from}/{to}/{c}/{s}/{ss}/{ps}/{check}/excel/date','SalesController@saleDatesExcel')->name('sales.saleDatesExcel');//excel for date diff
Route::get('/sales/search/{c}/{s}/{ss}/{check}/excel/ss','SalesController@saleSSExcel')->name('sales.saleSSExcel');//excel for year
Route::get('/sales/search/{c}/{s}/{ps}/{check}/excel/ps','SalesController@salePSExcel')->name('sales.salePSExcel');//excel for year
Route::get('/sales/search/{c}/excel/c','SalesController@saleCExcel')->name('sales.saleCExcel');//excel for year
Route::get('/sales/search/{sp}/excel/sp','SalesController@saleSPExcel')->name('sales.saleSPExcel');//excel for year

Route::get('/sales/report','SalesController@report')->name('sales.report');
Route::get('/sales/report/excel','SalesController@reportExcel')->name('sales.report.excel');
Route::post('/sales/report/search','SalesController@reportSearch')->name('sales.report.search');
Route::get('/sales/report/search/{Y}/{c}/{s}/{p}/{type}/{w}/{check}/excel/year','SalesController@reportExcelYExcel')->name('sales.report.saleYExcel');//excel for year
Route::get('/sales/report/search/{M}/{c}/{s}/{p/{type}}/{w}/{check}/excel/month','SalesController@reportExcelMExcel')->name('sales.report.saleMExcel');//excel for month
Route::get('/sales/report/search/{D}/{c}/{s}/{p}/{type}/{w}/{check}/excel/date','SalesController@reportExcelDExcel')->name('sales.report.saleDExcel');//excel for one date
Route::get('/sales/report/search/{from}/{to}/{c}/{s}/{p}/{type}/{w}/{check}/excel/date','SalesController@reportExcelDatesExcel')->name('sales.report.saleDatesExcel');//excel for date diff
Route::get('/sales/report/search/{c}/excel/c','SalesController@reportCExcel')->name('sales.report.reportExcelCExcel');//excel for year
Route::get('/sales/report/search/{p}/{type}/excel/p','SalesController@reportPExcel')->name('sales.report.reportExcelPExcel');//excel for year
Route::get('/sales/report/search/{w}/excel/w','SalesController@reportWExcel')->name('sales.report.reportExcelWExcel');//excel for year
Route::get('/sales/report/search/{sp}/excel/sp','SalesController@reportSPExcel')->name('sales.report.reportExcelSPExcel');

Route::get('/sales/pdf/{id}','SalesController@pdf')->name('sales.pdf');
Route::get('/sales/pdf','SalesController@pdf1');
Route::get('/sales/pos','SalesController@pos')->name('sales.pos');
Route::get('/sales/gdr/{no,id}','SalesController@GDR')->name('sales.GDR');
Route::get('/sales/gdr1/{no}','SalesController@GDR1');
Route::get('/sales/invoice/{id}','SalesController@invoice')->name('sales.invoice');
Route::get('/sales/product/{id}','SalesController@product')->name('sales.product');
Route::get('/sales/document/{id}','SalesController@document')->name('sales.document');
Route::get('/sales/gdn/{id}','SalesController@GDN')->name('sales.gdn');
Route::get('/sales/return/view','SalesController@returnView')->name('sales.return.view');
Route::get('/sales/return/show/{id}','SalesController@returnShow')->name('sales.return.show');
Route::resource('/sales','SalesController');
Route::post('/sales/status','SalesController@status')->name('sales.status');
Route::post('/sales/returnstatus','SalesController@returnStatus')->name('sales.returnstatus');
Route::post('/sales/delivery','SalesController@delivery')->name('sales.delivery');

resources/views/saleperson/create.blade.php
@extends('layouts.master')
@section('top-styles')
@toastr_css
@section('sidebar-name1')
<li class="breadcrumb-item"><a href="{{ url('')}}/saleperson">Sale Persons</a></li>
<li class="breadcrumb-item"><span>{{$isEdit ? 'Edit' : 'Add'}} Sale Person</span></li>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN VALIDATION STATES-->
            <div class="card" id="form_wizard_1">
                <div class="card-header">
                    <div class="caption">
                        <i class=" fa fa-user font-green"></i>
                        <span class="caption-subject font-green sbold uppercase">{{$isEdit ? 'Edit' : 'Add'}} Sale Person</span>
                    </div>

                </div>
                <div class="card-body">
                    <!-- BEGIN FORM-->
                    <form action="{{$isEdit ? route('saleperson.update',$vendor->id) :  route('saleperson.store')}} " class="form-horizontal" method="POST" id="salePersonForm">
                        @csrf
                        @if ($isEdit)
                            @method('PUT')
                        @endif
                        <div class="form-body">
                                <input type="hidden" name="u_id" value="{{$isEdit ? $vendor->u_id : $u_id}}">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-outline">
                                        <label >Sale Person Name<span class="text-danger">*</span></label>
                                        <input value="{{$vendor->name ?? old('name')}}" class="form-control" type="text" placeholder="Enter Name" name="name" required>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-outline">
                                        <label>Sale Person Type<span class="text-danger">*</span></label>
                                        <select name="p_type" required class="form-control js-example-basic-single" >
                                            <option value="" selected disabled>Select</option>
                                            @if ($isEdit)
                                                <option value="B2B" {{$vendor->p_type == 'B2B' ? 'selected' : null}}>B2B</option>
                                                <option value="Retail" {{$vendor->p_type == 'Retail' ? 'selected' : null}}>Retail</option>
                                            @else
                                                <option value="B2B" {{old('p_type') == 'B2B' ? 'selected' : null}} >B2B</option>
                                                <option value="Retail" {{old('p_type') == 'Retail' ? 'selected' : null}}>Retail</option>
                                            @endif
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="{{$isEdit ? 'col-sm-6' : (in_array('Add City',$permissions) ? 'col-sm-5' : 'col-sm-6')}}">
                                    <div class="form-outline">
                                        <label >City <small>(optional)</small></label>
                                        <select id="c_id" class="form-control js-example-basic-single"  name="c_id" >
                                            <option value="" disabled selected>Select...</option>
                                            @if ($isEdit ? '' : in_array('Add City',$permissions))
                                                <option>other</option>
                                            @endif
                                            @if ($isEdit)
                                                @foreach ($city as $s)
                                                <option {{$s->id == $vendor->c_id ? 'selected' : null}} value="{{$s->id}}">{{$s->c_name}}</option>
                                                @endforeach
                                            @else
                                                @foreach ($city as $s)
                                                <option value="{{$s->id}}" {{old('c_id') == $s->id ? 'selected' : null}}>{{$s->c_name}}</option>
                                                @endforeach
                                            @endif

                                        </select>
                                    </div>
                                </div>
                                @if ($isEdit ? '' : in_array('Add City',$permissions))
                                    <div class="col-sm-1">
                                        <div class="form-control" style="margin-top: 30px;  width:50px">
                                            <a href="#"  data-toggle="modal" data-target="#cityModal">
                                                <i class="fa fa-2x fa-plus-circle addIcon font-green"></i>
                                            </a>
                                        </div>
                                    </div>
                                @endif
                                <input type="hidden" name="v_type" value="Saleperson" id="">
                                <div class="col-sm-6">
                                    <div class="form-outline">
                                        <label >Address<span class="text-danger">*</span></label>
                                        <input value="{{$vendor->address ?? old('address')}}" class="form-control" type="text" placeholder="Enter Address" name="address" required>
                                        <span class="text-danger">{{$errors->first('address') ? 'Address already exist' : null}}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-outline">
                                        <label >Contact No<span class="text-danger">*</span></label>
                                        <input min="0" value="{{$vendor->c_no ?? old('c_no')}}" class="form-control" type="text" placeholder="Enter Contact Number" name="c_no" required>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-outline">
                                        <label >Email<span class="text-danger">*</span></label>
                                        <input value="{{$vendor->email ?? old('email')}}" required class="form-control" type="email" placeholder="Enter Email" name="email" >
                                        <span class="text-danger">{{$errors->first('email') ? 'email already exist' : null}}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-outline">
                                        <label >Password<span class="text-danger">*</span></label>
                                        <input value="" class="form-control" {{$isEdit ? '' : 'required'}} type="password" placeholder="Enter Password" name="password" >
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-outline">
                                        <label>Commission in(%) <span class="text-danger">*</span></label>
                                        <input type="text" class="form-control" required name="commission" value="{{$vendor->commission ?? old('commission')}}">
                                    </div>
                                </div>
                            </div>
                            <br>
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-0">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </div>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
            <!-- END VALIDATION STATES-->
        </div>
    </div>
    @include('modals.city')
@endsection
@section('custom-script')
@toastr_js
@toastr_render
<script>
    $(document).ready(function(){
        $('.js-example-basic-single').select2();
        $('#c_id').change(function() { //jQuery Change Function
            var opval = $(this).val(); //Get value from select element
            console.log(opval);
            if(opval=="other"){ //Compare it and if true
                $('#cityModal').modal("show"); //Open Modal
            }
        });
    });
</script>
<script>
    $('#salePersonForm').validate({
        rules: {
            name: {
                required: true,
            },
            p_type: {
                required: true,
            },
            address: {
                required: true,
            },
            email: {
                required: true,
            },
            password: {
                required: true,
            },
            commission: {
                required: true,
            },
            c_no: {
                required: true,
            },

        },
        errorElement: 'span',
        errorPlacement: function (error, element) {
            error.addClass('invalid-feedback back_error');
            element.closest('.form-outline').append(error);
        },
        highlight: function (element, errorClass, validClass) {
            $(element).addClass('is-invalid');

        },
        unhighlight: function (element, errorClass, validClass) {
            $(element).removeClass('is-invalid');
        }
    });
</script>
@endsection

resources/views/saleperson/pdf.blade.php
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <style>
      .attendance-table table{
        width: 100%;
        border-collapse: collapse;
        border: 1px solid #000;
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        }

        .blank-cell{

        min-width: 50px;


        }

        .attendance-cell{

        padding: 8px;


        }

        .attendance-table table th.attendance-cell, .attendance-table table td.attendance-cell {
            border: 1px solid #000;
        }
  </style>

  <body>
    <div class="attendance-table">
        <h3>Sale Persons Information</h3>
        <table class="table-bordered">

            <tr>
                <th class="attendance-cell">S.NO</th>
                <th class="attendance-cell">Name</th>
                <th class="attendance-cell">Email</th>
                <th class="attendance-cell">Address</th>
                <th class="attendance-cell">Contact No</th>
            </tr>
            @php
                $count = 1;
            @endphp
            @foreach($vendor as $user)
                <tr>
                    <td class="attendance-cell">{{ucwords($count)}}</td>
                    <td class="attendance-cell">{{ucwords($user->name)}}</td>
                    <td class="attendance-cell">{{ucwords($user->email)}}</td>
                    <td class="attendance-cell">{{ucwords($user->address)}}</td>
                    <td class="attendance-cell">{{$user->c_no}}</td>
                </tr>
                @php
                    $count++;
                @endphp
            @endforeach

        </table>

    </div>
  </body>
</html>